---
title: "Fair Distribution of Specialists: Hospital Inpatient Workload 2019"
description: |
  ***Curated by Dr Saiful Safuan Md Sani*** 
  <br> _MRCP(London) MRCP(UK) MA(Cantab) MBBS(London)_
  <br> _Consultant Physician (Acute Internal Medicine)_
site: distill::distill_website
---
<style type="text/css">
body{ /* Normal  */
      font-size: 8px;
  }
</style>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```
***Workload dictates amount of manpower.***


<br>
<br> **Standardised Workload = Number of specialists per 1000 admissions.**
<br>
<br> $${Standardised\;Workload = {Number\;of\; specialists} \div \left( \displaystyle \frac{Admissions}{1000}\right)}$$
<br>
<br> *e.g. HKL has 60 specialists handling General Medicine workload, for the given number of admissions in HKL (37,067), it has 1.6 specialists handling every 1000 admissions.*

<br>

**CAUTION**: fair distribution requires consideration and information on:
<br> 1. outpatient clinic volume, 
<br> 2. daycare volume,
<br> 3. procedure volume,
<br> 4. referral workload, 
<br> 5. fulfilling demands for up-to-date treatment provided by a subspecialty.

<br>

**Peculiarities**
<br> Medical subspecialties within state and major government hospitals in Malaysia have different administration configuration. Hence admissions workload are categorised into two: ***shared admissions workload*** and ***all-in admissions workload***. In shared admissions workload, admissions workload are handled by general medicine and certain medical subspecialties. Participating medical subspecialities vary between centres. In all-in admissions workload, all admissions into general medicine and medical subspecialties are pooled together, along with pooled manpower.

<br>
